//math functions

//The Math namespace object contains static properties and methods for 
//mathematical constants and functions.

console.log(Math.PI)
console.log(Math.round(6.8))
console.log(Math.abs(-7356))
console.log(Math.ceil(5.7))
console.log(Math.floor(7.6))

/*Static methods
Math.abs()
Math.acos()
Math.acosh()
Math.asin()
Math.asinh()
Math.atan()
Math.atan2()
Math.atanh()
Math.cbrt()
Math.ceil()
Math.clz32()
Math.cos()
Math.cosh()
Math.exp()
Math.expm1()
Math.f16round()
Math.floor()
Math.fround()
Math.hypot()
Math.imul()
Math.log()
Math.log10()
Math.log1p()
Math.log2()
Math.max()
Math.min()
Math.pow()
Math.random()
Math.round()
Math.sign()
Math.sin()
Math.sinh()
Math.sqrt()
Math.tan()
Math.tanh()
Math.trunc()
*/